# Generated by Django 3.2.8 on 2021-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_timeslottable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslottable',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
