# Generated by Django 3.2.8 on 2021-11-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=50)),
                ('turf_place', models.CharField(max_length=50)),
                ('turf_morningPrice', models.IntegerField()),
                ('turf_eveningPrice', models.IntegerField()),
                ('turf_number', models.CharField(max_length=10)),
                ('turf_address', models.CharField(max_length=70)),
            ],
        ),
    ]
